sudo: false
language: python
cache:
  directories:
  - "${HOME}/gcloud/"
env:
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=${PATH}:${HOME}/gcloud/google-cloud-sdk/bin
  PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- if [ ! -d ${HOME}/gcloud/google-cloud-sdk ]; then
  mkdir -p ${HOME}/gcloud &&
  wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=${HOME}/gcloud &&
  cd ${HOME}/gcloud &&
  tar xzf google-cloud-sdk.tar.gz &&
  printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
  cd ${TRAVIS_BUILD_DIR};
  fi
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- openssl aes-256-cbc -K $encrypted_d353a6b37540_key -iv $encrypted_d353a6b37540_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d "${GAE_PYTHONPATH}" ]; then python scripts/fetch_gae_sdk.py $(dirname
  "${GAE_PYTHONPATH}"); fi
- rm -rf /home/travis/google-cloud-sdk
- curl https://sdk.cloud.google.com | bash;
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json
install:
- gcloud config set project testautodeploy
- gcloud -q components update gae-python
- pip install -r requirements.txt -t lib/
script:
- python test_main.py
- gcloud -q preview app deploy app.yaml --promote
- python e2e_test.py
